### ISSUE TITLE
Sidebar nav items are opening in a new window

### ISSUE THREAD

**Issue by jaredcwhite** [ParamagicDev/webpacker-docs-proxy#2]
I think it has something to do with this:

https://github.com/ParamagicDev/webpacker-docs-proxy/blob/b2471cdb7340f89112bfa145b8ad6474130586e0/frontend/javascript/controllers/document_link_controller.js#L21

Site looks way cool otherwise!

**Comment by jaredcwhite** [comment]
Duh, you already have an issue for this. NM!

**Comment by KonnorRogers** [comment]
Thanks @jaredcwhite ! Yea a few kinks to iron out for sure, not bad for one day of dev while at work!
